# -*- coding: utf-8 -*-
"""Mini Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnTun4WFCWihpALZ6G5je73mjocigpKE
"""

import pandas as pd
df_roi = pd.read_csv('/content/roi_data.csv')
df_spend = pd.read_csv('/content/spend_data.csv')

df_roi.head(5)
df_spend.head(5)

print(df_roi.isnull().sum())
print(df_spend.isnull().sum())

#merge data on basis of channel & Month

df = pd.merge(df_roi, df_spend, on='Channel')
df.head(5)

df["ROI per Spend"] = df["ROI"] / df["Spend"]

print(df)

#A pivot table (average ROI & Spend by Category).
df["Category"] = df["Channel"].map({
    "Email": "Organic",
    "SEO": "Organic",
    "Paid Ads": "Paid", "Social Media": "Paid", "Referrals" : "Organic", "Display Ads": "Paid", "Influencers": "Organic"
})

pivot = pd.pivot_table(df, values=["ROI", "Spend"], index="Category", aggfunc="mean")
print(pivot)

#A bar chart (ROI per Channel).
import matplotlib.pyplot as plt

# Bar chart ROI per channel
df.plot(kind="bar", x="Channel", y="ROI", legend=False)
plt.title("ROI per Channel")
plt.ylabel("ROI")
plt.show()

# Bar chart ROI per category
pivot.plot(kind="bar")
plt.title("Average ROI by Category")
plt.ylabel("ROI")
plt.show()

# Export pivot table to CSV
pivot.to_csv("pivot_summary.csv")

# Export full DataFrame to Excel
df.to_excel("marketing_analysis.xlsx", index=False)